name: Check pull requests

on: [workflow_dispatch]

jobs:

  check:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: arch4edu/cactus/actions/upgrade-archlinux@main

      - name: Install runtime dependencies
        run: pacman -S --noconfirm --needed git nvchecker python-requests python-toml

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Check nvchecker.toml
        run: |
          git config --global --add safe.directory $(realpath .)
          sed "s/__GITHUB_TOKEN__/${{ secrets.GITHUB_TOKEN}}/" -i keyfile.toml
          python check-pr.py
